version: 2.1

# Define the jobs we want to run for this project##
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  test-and-deploy: # workflow 이름
    jobs:
      - test  # test job
      - deploy:
          requires: # test가 끝나야 deploy 실행
              - test
          filters:
              branches:
                only: main # main 브랜치에 push 됐을 때만 실행