version: 2.1

jobs:

  Gradle_Test_and_Build_Push:
    docker:
      - image: cimg/openjdk:17.0.11


    steps:
      - checkout

      - run:
          name: Set up JDK 17
          command: |
            echo "Java version:"
            java -version

      - run:
          name: Set up Gradle
          command: |
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 7.3.1
            
      - run:
          name: Set up application.properties
          command: echo "${PROPERTIES}" > ./src/main/resources/application.properties

      - run:
          name: Gradle Build Authorization
          command: chmod +x ./gradlew

      - run:
          name: Run unit tests
          command: ./gradlew test

      - store_artifacts:
          path: build/reports/tests/test
          destination: unit-test-report

      - run:
          name: Build with Gradle
          command: ./gradlew build

      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_HUB_TOKEN" | docker login -u sppaul --password-stdin

      - run:
          name: Build Docker image
          command: docker build -t test ./

      - run:
          name: Push Docker image
          command: docker push sppaul/cicd:latest

  # deploy_docker_ec2 Job 정의
  deploy_docker_ec2:
    docker:
      - image: circleci/python:3.8  # EC2 배포를 위한 이미지 선택

    steps:
      - run:
          name: Deploy Docker on EC2
          command: |
            sudo apt-get update
            sudo apt-get install -y openssh-client
            echo "$EC2_SSH_PRIVATE_KEY" > private_key.pem
            chmod 400 private_key.pem
            ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_HOST \<<< 'EOF'
              sudo docker rm -f $(docker ps -qa)
              sudo docker pull sppaul/cicd:latest
              docker-compose down
              docker-compose -f /home/ubuntu/docker-compose.yml up --build -d
              docker-compose -f /home/ubuntu/docker-compose.yml up -d
              docker image prune -f
            EOF
workflows:
  version: 2
  deploy:
    jobs:
      - Gradle_Test_and_Build_Push
      - deploy_docker_ec2:
          requires:
            - Gradle_Test_and_Build_Push
